### ISSUE TITLE
New sign in with every on-site chat

### ISSUE THREAD

**Issue by josephahaden** [WordPress/matrix#1]
### Expected Behavior

I was testing the on-site chat integrations this morning and expected to be able to log into the server once and be able to participate in all chats from there.

### Actual Behavior

<img width="725" alt="Screenshot 2023-11-29 at 8 43 13 AM" src="https://github.com/WordPress/Matrix/assets/1886921/56e8c3ef-a1b8-45a6-a33e-7bfdf7bdd7a4">

Instead, I get a new sign in for every chat I open. It shows the screen above first, but won't let me reuse any of the sessions. Then when I click "Sign In" it redirects as normal and creates a new one.

### Steps to Reproduce

1. Go to make.wordpress.org
2. Click a meeting link to go to a room
3. Go back to make.wordpress.org
4. Click a different meeting link to go to a different room

**Comment by akirk** [comment]
For some reason, your browser is not reusing the already existing session. Could you please try to log out of all the additional sessions like this?

When presented with the selection, open one of the 4 accounts and you'll arrive inside the room. Then go to settings like this:
![Screenshot 2023-11-29 at 15 54 18](https://github.com/WordPress/Matrix/assets/203408/02ec9ee2-bf5d-4413-98cf-e939fee4e856)
and then log out of that session:
![Screenshot 2023-11-29 at 15 54 23](https://github.com/WordPress/Matrix/assets/203408/23aec422-30cb-46f6-b320-88c01d33e2a6)

When you're down to a single session, it should not prompt you to select one when you open the chat but go into the room straight away.

**Comment by josephahaden** [comment]
That worked! I'm now down to one session. 🎉

**Comment by psrpinto** [comment]
@josephahaden Any chance you remember which page you were at when you logged-in the first time? If so, could you post the URL of the page?

**Comment by psrpinto** [comment]
We have identified a solution for this and will be issuing a fix ASAP.

**Comment by psrpinto** [comment]
We have produced a fixed. Reopening for now since it's not yet deployed. Deploying ASAP.

**Comment by psrpinto** [comment]
Fix has been deployed. Users will now never see the "session picker" screen, and will instead automatically be logged-in to an existing session, if there is one.

If user had multiple sessions (as per this issue), all but one will be automatically removed, and they will be logged-in to the remaining one.

Additionally, if there is no session, users will now see the login screen directly, instead of first having to click "Sign in" in the session picker.
