### ISSUE TITLE
It's possible to leave Announcements

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/matrix#17]
### Expected Behavior

Users must stay in announcements in order to receive announcements. 

### Actual Behavior

You can leave the channel

**Comment by akirk** [comment]
While it is possible with https://github.com/devture/matrix-corporal/ to force people to be in certain rooms, I wonder if it makes sense due to how people might be using chat with Matrix, i.e. they might just [use the P2 chat pages](https://make.wordpress.org/chat/matrix/using-a-p2-chat-page/).
