### ISSUE TITLE
Matrix doesn't appear to have ability to mute a channel

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/matrix#18]
### Expected Behavior

Slack allows you to mute a channel so you can be "in" the channel but only get alerted/notified on things you need to be (channel/here messages, notification words, @messages) but Matrix doesn't appear to have similar functionality so you just end up seeing a LOT of channels with no way to best attend to the important alerts/notifications to find the messages you REALLY need to attend to.

### Actual Behavior

Matrix appears to only have Rooms and ability to mark some as Low priority, but otherwise no way to mute a channel.

**Comment by akirk** [comment]
In Element this is called Low Priority, see this [guide page](https://make.wordpress.org/chat/matrix/chatting-in-matrix-using-element/#stop-notifications-for-a-room), pasting the screenshot here:

![element-low-priority](https://github.com/WordPress/Matrix/assets/203408/13fbb2db-af7c-43d8-8688-d7922baf2138)

**Comment by jeffpaul** [comment]
Right, that's about the best we can do in Element though Low Priority still has the channels appear in the grouping of the same name and I'm not sure what happens if I get @mentioned in one of those channels whether it would move from Low Priority into the main room listing so that I see I've got a ping in that channel?

**Comment by akirk** [comment]
You can still set the notification options for low priority rooms:
![Screenshot 2023-12-04 at 17 45 43](https://github.com/WordPress/Matrix/assets/203408/3fa1a4a9-c21d-4341-8d8e-de6be37427d7)

**Comment by jeffpaul** [comment]
Looks like either Element changed their notification handling (or I've yet to receive an update that you're seeing):

![Screenshot 2023-12-04 at 11 38 53 AM](https://github.com/WordPress/Matrix/assets/2818133/92b5abee-f217-4e21-8112-44a58e19fa31)

**Comment by akirk** [comment]
This is per room. You need to over hover a room and then you can see the bell icon as I indicated.

**Comment by jeffpaul** [comment]
Ah nice, thanks for the tip there!

I wonder if it would be helpful to start capturing some FAQs on how to configure Matrix (or Matrix clients) to match similar functionality within Slack?

**Comment by akirk** [comment]
I already described a couple of things in Element here: https://make.wordpress.org/chat/matrix/chatting-in-matrix-using-element/

For migrating from Slack specifically, I also created https://make.wordpress.org/chat/matrix/tips-for-transitioning-from-slack-to-matrix/, maybe it'd be good to mention this on there too.

These are both linked from https://make.wordpress.org/chat/matrix/

**Comment by akirk** [comment]
Closing this functionality has been explained.

**Comment by jeffpaul** [comment]
@akirk as a test, I have the #docs room in Matrix "muted".  Would you please @mention me in that room so I can see if Matrix will properly alert me to that reference?
