### ISSUE TITLE
No notification or indication of Slack direct messages

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/matrix#26]
### Expected Behavior

A contributor has sent me a direct message. I can see it in Slack, but not via Matrix/Element. I'm not sure if this is a Matrix restriction, or an Element one.

### Steps to Reproduce

Have someone send a DM via WordPress Slack, it does not seem to appear in the Element client. I would expect a notification under the People tab. 

### Environment

- MacOS (Sonoma)
- Element client 1.11.51

**Comment by akirk** [comment]
The bridge doesn't have any kind of access to anyone's DMs. Therefore, it cannot know that you received a DM and thus not relay it to Matrix.
