### ISSUE TITLE
Cannot complete OIDC flow due to error

### ISSUE THREAD

**Issue by psrpinto** [WordPress/matrix#6]
### Expected Behavior

User `javiercasares` is able to complete OIDC flow so that they can access the Matrix server.

### Actual Behavior

At https://login.wordpress.org/wp-json/openid-connect/authorize, the browser shows an error:

```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

### Steps to Reproduce

1. Go to https://make.wordpress.net/meta/chat
2. Click "Continue with WordPress.org"
3. Click "Authorize" when asked to grant access
4. The browser shows the error described above

### Screenshots

![Screenshot_79](https://github.com/WordPress/Matrix/assets/550401/a8e81031-e9d9-467f-b33f-76217005e20a)

**Comment by ashfame** [comment]
User `tobiasbg` also [reported](https://matrix.to/#/!rJDndiwceRkJQdUavC:community.wordpress.org/$lrfL_RjzlckVmAl0JEThgKsbcyt11DrKOd-X1fs1ovs?via=community.wordpress.org&via=kirk.at) a white screen on authorize endpoint.
